### ISSUE TITLE
代码简单的高亮

### ISSUE THREAD

**Issue by iOSleep** [DianQK/Gitai#2]
> iPhone 7 Plus 11.2 Gitai 1.0.0(7).

**Comment by DianQK** [comment]
@iOSleep 具体一些？

**Comment by iOSleep** [comment]
平时看oc和swift的代码多点，能高亮就好了




  
  
  


  
    
      
          
            
              
            
            
              马旭
            
          
            
              
                  邮箱：mx.yolande@gmail.com
              
            
      
    
  


签名由 网易邮箱大师 定制
在2017年12月15日 10:41，DianQK 写道： @iOSleep 具体一些？

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DianQK/Gitai","title":"DianQK/Gitai","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/DianQK/Gitai"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DianQK in #2: @iOSleep 具体一些？"}],"action":{"name":"View Issue","url":"https://github.com/DianQK/Gitai/issues/2#issuecomment-351897631"}}}

**Comment by DianQK** [comment]
高亮已经有了，基于 prismjs
